add .
moolio-18/raisetech pull request #3
Opened 2024-06-24 14:40 UTC by moolio-18

# 第４回課題提出

ご確認お願いします。

2024-06-24 15:07 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-06-24 15:07 UTC, MasatoshiMizumoto commented on images04/rds.png
DBはインターネットに公開しないのがセオリーなので、見直しをお願いします！

2024-06-25 13:18 UTC, moolio-18 commented
修正点をlecture.mdの一番後ろに追記しています。
インターネットに公開の状態になっている、とのことで設定を見直したのですが
認識あってますでしょうか？ご確認お願いいたします。

2024-06-25 14:15 UTC, MasatoshiMizumoto approved these changes
LGTMです！
RDSはプライベートサブネットに配置してパブリック接続しないのがベーシックな利用方法なので、今後ご注意ください！

2024-06-26 11:34 UTC, merged